AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  line-dynamo-lambda
  
  Sample SAM Template for line-dynamo-lambda
Description: >
  Sample function
Parameters: 
  LineBotChannelSecret:
    Type: String
  LineBotChannelToken:
    Type: String
  SlackOauthToken:
    Type: String
  SlackSigingSecret:
    Type: String

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 5
    Tracing: Active
  Api:
    TracingEnabled: True

Resources:
  RestApi:
    Type: AWS::Serverless::Api # API Gateway
    Properties:
      StageName: Dev # デプロイするステージ名
      DefinitionBody:
        Fn::Transform:
          Name: AWS::Include
          Parameters:
            Location: ./src/swagger.yml # swaggerファイルのパス指定
      
  HelloWorldFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: cmd/line-bot-memo/
      Handler: line-bot-memo
      Runtime: go1.x
      Architectures:
        - x86_64
      Events:
        CatchAll:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /line-bot
            Method: POST
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          LINE_BOT_CHANNEL_SECRET: !Ref LineBotChannelSecret
          LINE_BOT_CHANNEL_TOKEN: !Ref LineBotChannelToken
          TABLE_NAME: sample_table

  SlackFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: cmd/slack-bot-memo/
      Handler: slack-bot-memo
      Runtime: go1.x
      Architectures:
        - x86_64
      Events:
        CatchAll:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /slack-bot
            Method: POST
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          LINE_BOT_CHANNEL_SECRET: !Ref LineBotChannelSecret
          LINE_BOT_CHANNEL_TOKEN: !Ref LineBotChannelToken
          SLACK_OAUTH_TOKEN: !Ref SlackOauthToken
          SLACK_SIGNING_SECRET: !Ref SlackSigingSecret

  SlackInteractiveFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: cmd/slack-bot-memo-interactive/
      Handler: slack-bot-memo
      Runtime: go1.x
      Architectures:
        - x86_64
      Events:
        CatchAll:
          Type: Api
          Properties:
            Path: /slack-bot/interactive
            Method: POST
            RestApiId: !Ref RestApi # RestApiの定義を参照
      Environment:
          LINE_BOT_CHANNEL_SECRET: !Ref LineBotChannelSecret
          LINE_BOT_CHANNEL_TOKEN: !Ref LineBotChannelToken
          SLACK_OAUTH_TOKEN: !Ref SlackOauthToken
          SLACK_SIGNING_SECRET: !Ref SlackSigingSecret

  SampleTable:
    Type: AWS::DynamoDB::Table
    Properties: 
      TableName: sample_table
      AttributeDefinitions: 
        - AttributeName: sample_pk
          AttributeType: S
        - AttributeName: sample_sk
          AttributeType: N
      KeySchema: 
        - AttributeName: sample_pk
          KeyType: HASH
        - AttributeName: sample_sk
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  HelloWorldAPI:
    Description: "API Gateway endpoint URL for Prod environment for First Function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  HelloWorldFunction:
    Description: "First Lambda Function ARN"
    Value: !GetAtt HelloWorldFunction.Arn
  HelloWorldFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt HelloWorldFunctionRole.Arn
