openapi: 3.0.1
info:
  description: 'REST API 定義'
  version: '1.0.0'
  title: 
    Fn::Sub: ${AWS::StackName}_restApi # API Gatewayに生成されるAPI名
paths:
  /slack-bot/interactive: # APIのパス
    post:
      summary: 'slackbotからのactionメッセージを処理するAPI'
      parameters: []
      requestBody: # bodyでデータを受け取る
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/payload'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/payload'
      responses:
        200:
          description: '成功時のレスポンス'
      x-amazon-apigateway-integration:
        uri:
          uri: !Sub arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${PostFunc.Arn}/invocations
        passthroughBehavior: when_no_templates
        httpMethod: POST
        type: aws
        contentHandling: CONVERT_TO_TEXT
        requestTemplates:
          application/x-www-form-urlencoded: "{\"body\": $input.json(\"$\")}"
          
components:
  schemas:
    payload: 
      type: object
      properties: 
        actions: 
          type: array
          items:
            $ref: '#/components/schemas/action'
        callback_id:
          type: string 
        user: 
          type: object
          properties: 
            id: string
            name: string
    action: 
      type: object 
      properties:
        name:
          type: string
        value:
          type: string
        type:
          type: string
    
    device: # {'SerialNumber': 'abc-001', 'type': 1, 'status': 'working', 'power': 50}を定義
      type: object
      properties:
        SerialNumber:
          type: string
        type:
          type: integer
        status:
          type: string
        power:
          type: integer
    deviceList: # deviceのListを定義
      type: object
      properties:
        items:
          type: array
          items:
            $ref: '#/components/schemas/device'